language: cpp
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=debug
  - TEST_TYPE=normal
  - TEST_TYPE=coverage
  - TEST_TYPE=asan
  - TEST_TYPE=docs
script:
  - travis lint .travis.yml --skip-completion-check
  - docker run -t -i -v $TRAVIS_BUILD_DIR:/source lyft/envoy-build:latest /bin/bash -c "cd /source && ci/do_ci.sh $TEST_TYPE"
after_success:
  - ./ci/docker_push.sh
